import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {Deta, Drive} from "deta";


const inter = Inter({subsets: ['latin']})
const deta = Deta("a04e75yrens_KhQjJm4oPhH2ukjKSw36MGWNuVEhVqkQ");
const drive = deta.Drive("drive01");

// get image from url and save to buffer, then upload to drive
async function uploadImage(url) {
    let response = await fetch(url);
    console.log(response)
    const buffer = await response.buffer();
    const name = url.split('/').pop();
    const file = drive.put(name, buffer);
    return file;
}

// handle button click and upload image
async function handleClick() {
    console.log("clicked")
    const url = "https://i.pixl.li/Mars-Noire-19528a9cdaa045d947a.jpg";
    const file = await uploadImage(url);
    console.log(file);
}


export default function Home() {
    return (
        <>
            <Head>
                <title>remote-upload</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <div>
                    <input type="text" placeholder="Type here" className="input w-full max-w-xs"/>
                    <button className="btn" onClick={handleClick}>upload</button>
                </div>

            </main>
        </>
    )
}
